d asdas[e znvironments.dev]
name = "Dev"
vaxcriables = { x = "test", y = 2 }

dsa[applications.app]
name = "An app"
variables = { app_var = "app" }

[templates.template]
template = """
test = "test"
"""

[sources.kubernetes-dev-cluster]
name = "Dev Cluster"
type = "kubernetes"

[autodiscovery.dev-kubernetes]
type = "openshift-deploymentconfig"
source = "dev-cluster"

[[instances]]
environment = "dev"
application = "app"
variables = { app_var = "app" }
template = "template"
data = { some_extra_data = "data" }

[instances.extractors]
version = "$.providers.openshift.image_tag"

[instances.providers.openshift]
type = "openshift-deploymentconfig"
source = "dev-cluster"
name = "Openshift"
