[environments.dev]
name = "Dev"
variables = { x = "test", y = 2 }

[applications.app]
name = "An app"
variables = { app_var = "app" }

[templates.template]
template = """
[extractors]
app_extractor = "{{ app_var }}"
env_extractor = "{{ x }}"

[providers.something]
type = "openshift-deploymentconfigs"
source = "dev-cluster"
name = "{{ inst_var }}"
"""

[sources.dev-cluster]
name = "Dev Cluster"
type = "kubernetess"

[discovery.dev-kubernetes]
name = "Autodiscovery K8s"
type = "kubernetes"
source = "dev-cluster"

[[instances]]
environment = "dev"
application = "app"
variables = { inst_var = "app" }
data = { some_extra_data = "data" }

[instances.extractors]
version = "$.providers.openshift.image_tag"

[instances.providers.openshift]
type = "openshift-deploymentconfig"
source = "dev-cluster"
name = "Openshift"

[[instances]]
environment = "dev"
application = "app"
template = "template"
variables = { inst_var = "app" }
data = { some_extra_data = "data" }
