[environments.dev]
name = "Dev"
variables = { x = "test", y = 2 }

[applications.app]
name = "An app"
variables = { app_var = "app" }

[templates.template]
template = """
[extractors]
full_extractor = "$.some_extra_data"
env_extractor = "{{ x }}"

[providers.something]
type = "kubernetes"
source = "dev-cluster"
name = "{{ inst_var }}"
"""

[sources.dev-cluster]
name = "Dev Cluster"
type = "kubernetess"

[sources.http-test]
name = "HTTP test"
type = "http"

[sources.http-test.config]
auth_type = "bearer" # bearer | basic | none
username = "name"
password = "token"
# tls_insecure = true
# tls_cacert = ""
# tls_cacert_file = ""
# bearer = ""
# bearer_file = ""
# extra_headers = []

[discovery.dev-kubernetes]
name = "Autodiscovery K8s"
type = "kubernetes"
source = "dev-cluster"

[[instances]]
environment = "dev"
application = "app"
variables = { inst_var = "app" }
data = { some_extra_data = "data" }

[instances.extractors]
version = "$.providers.openshift.image_tag"

[instances.providers.openshift]
type = "openshift-deploymentconfig"
source = "dev-cluster"
name = "Openshift"

[[instances]]
environment = "dev"
application = "app"
template = "template"
variables = { inst_var = "app" }
data = { some_extra_data = "data2" }
